### ISSUE TITLE
将支持的 KMS 云服务使用选相框标注哪些已支持哪些不支持

### ISSUE THREAD

**Issue by leinue** [Authing/kms-typeorm#1]
将支持的 KMS 云服务使用选相框标注哪些已支持哪些不支持，如下所示：

- [x] AWS KMS
- [ ] 腾讯云 KMS

这样能让读者清晰的了解框架现状 @liaochangjiang

**Comment by liaochangjiang** [comment]
https://github.com/Authing/kms-typeorm/commit/32c4dcd123a86e4d8f26c5a818121479f6c764d8 已修改
